# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimateLong_cpp <- function(in_list) {
    .Call('LANGlong_estimateLong_cpp', PACKAGE = 'LANGlong', in_list)
}

samplePosteriorGH <- function(obs_list, operator_list, theta_list, mixed_list, V_list, nsim, noise, commonsigma) {
    .Call('LANGlong_samplePosteriorGH', PACKAGE = 'LANGlong', obs_list, operator_list, theta_list, mixed_list, V_list, nsim, noise, commonsigma)
}

simulateLong_cpp <- function(obs_, operator_, theta_) {
    .Call('LANGlong_simulateLong_cpp', PACKAGE = 'LANGlong', obs_, operator_, theta_)
}

testSimulateX_cpp <- function(operator_, theta_) {
    .Call('LANGlong_testSimulateX_cpp', PACKAGE = 'LANGlong', operator_, theta_)
}

testSimulateX2_cpp <- function(operator_, theta_) {
    .Call('LANGlong_testSimulateX2_cpp', PACKAGE = 'LANGlong', operator_, theta_)
}

simulateLongGH_cpp <- function(obs_list, operator_list, theta_list) {
    .Call('LANGlong_simulateLongGH_cpp', PACKAGE = 'LANGlong', obs_list, operator_list, theta_list)
}

