# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimateLong_cpp <- function(in_list) {
    .Call('LANGlong_estimateLong_cpp', PACKAGE = 'LANGlong', in_list)
}

predictLong_cpp <- function(in_list) {
    .Call('LANGlong_predictLong_cpp', PACKAGE = 'LANGlong', in_list)
}

simulateLongGH_cpp <- function(in_list) {
    .Call('LANGlong_simulateLongGH_cpp', PACKAGE = 'LANGlong', in_list)
}

estimateProcess_cpp <- function(in_list) {
    .Call('LANGlong_estimateProcess_cpp', PACKAGE = 'LANGlong', in_list)
}

