// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// sample_Nccpp
Eigen::VectorXd sample_Nccpp(Eigen::VectorXd b, Eigen::MatrixXd Q);
RcppExport SEXP GHmixedeffect_sample_Nccpp(SEXP bSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type b(bSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Q(QSEXP);
    __result = Rcpp::wrap(sample_Nccpp(b, Q));
    return __result;
END_RCPP
}
// simulateNoise
Rcpp::List simulateNoise(Rcpp::List input);
RcppExport SEXP GHmixedeffect_simulateNoise(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type input(inputSEXP);
    __result = Rcpp::wrap(simulateNoise(input));
    return __result;
END_RCPP
}
// simulateMixed
Rcpp::List simulateMixed(Rcpp::List input);
RcppExport SEXP GHmixedeffect_simulateMixed(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type input(inputSEXP);
    __result = Rcpp::wrap(simulateMixed(input));
    return __result;
END_RCPP
}
// estimateME
Rcpp::List estimateME(Rcpp::List input);
RcppExport SEXP GHmixedeffect_estimateME(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type input(inputSEXP);
    __result = Rcpp::wrap(estimateME(input));
    return __result;
END_RCPP
}
// samplePostV
Eigen::VectorXd samplePostV(Rcpp::List input);
RcppExport SEXP GHmixedeffect_samplePostV(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type input(inputSEXP);
    __result = Rcpp::wrap(samplePostV(input));
    return __result;
END_RCPP
}
// estimateNIGnoise
Rcpp::List estimateNIGnoise(Rcpp::List input);
RcppExport SEXP GHmixedeffect_estimateNIGnoise(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type input(inputSEXP);
    __result = Rcpp::wrap(estimateNIGnoise(input));
    return __result;
END_RCPP
}
// EstimateFisherInformation
Rcpp::List EstimateFisherInformation(Rcpp::List input);
RcppExport SEXP GHmixedeffect_EstimateFisherInformation(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type input(inputSEXP);
    __result = Rcpp::wrap(EstimateFisherInformation(input));
    return __result;
END_RCPP
}
