# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

traceWithLUSparse <- function(A, B) {
    .Call('solvercpp_traceWithLUSparse', PACKAGE = 'solvercpp', A, B)
}

traceWithLU <- function(A, B) {
    .Call('solvercpp_traceWithLU', PACKAGE = 'solvercpp', A, B)
}

solveWithLU <- function(A, b) {
    .Call('solvercpp_solveWithLU', PACKAGE = 'solvercpp', A, b)
}

logdetWithLU <- function(A) {
    .Call('solvercpp_logdetWithLU', PACKAGE = 'solvercpp', A)
}

LU_sparse_logdet <- function(A) {
    .Call('solvercpp_LU_sparse_logdet', PACKAGE = 'solvercpp', A)
}

LU_sparse_tests <- function(init_list_in) {
    .Call('solvercpp_LU_sparse_tests', PACKAGE = 'solvercpp', init_list_in)
}

solver_tests <- function(init_list_in) {
    .Call('solvercpp_solver_tests', PACKAGE = 'solvercpp', init_list_in)
}

kronecker_tests <- function(init_list_in) {
    .Call('solvercpp_kronecker_tests', PACKAGE = 'solvercpp', init_list_in)
}

vech_cpp <- function(A) {
    .Call('solvercpp_vech_cpp', PACKAGE = 'solvercpp', A)
}

veci_cpp <- function(vecA, n) {
    .Call('solvercpp_veci_cpp', PACKAGE = 'solvercpp', vecA, n)
}

vec_cpp <- function(A) {
    .Call('solvercpp_vec_cpp', PACKAGE = 'solvercpp', A)
}

duplicatematrix_cpp <- function(A) {
    .Call('solvercpp_duplicatematrix_cpp', PACKAGE = 'solvercpp', A)
}

