# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_Nccpp <- function(b, Q) {
    .Call('GHmixedeffect_sample_Nccpp', PACKAGE = 'GHmixedeffect', b, Q)
}

simulateNoise <- function(input) {
    .Call('GHmixedeffect_simulateNoise', PACKAGE = 'GHmixedeffect', input)
}

simulateMixed <- function(input) {
    .Call('GHmixedeffect_simulateMixed', PACKAGE = 'GHmixedeffect', input)
}

estimateME <- function(input) {
    .Call('GHmixedeffect_estimateME', PACKAGE = 'GHmixedeffect', input)
}

samplePostV <- function(input) {
    .Call('GHmixedeffect_samplePostV', PACKAGE = 'GHmixedeffect', input)
}

estimateNIGnoise <- function(input) {
    .Call('GHmixedeffect_estimateNIGnoise', PACKAGE = 'GHmixedeffect', input)
}

