# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_Nccpp <- function(b, Q) {
    .Call('GHmixedeffect_sample_Nccpp', PACKAGE = 'GHmixedeffect', b, Q)
}

estimateME <- function(input) {
    .Call('GHmixedeffect_estimateME', PACKAGE = 'GHmixedeffect', input)
}

